version: '3'

services:
  backend:
    build: 
      context: Backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    env_file:
      - .db_env
  nginx-react:
    depends_on:
      - backend
    container_name: ngixreactapp
    build:
      context: ./Frontend/time_tracker/
      dockerfile: Dockerfile
    ports:
      - 80:80
#  nginx:
#    image: sha256:4900b3b015c807b67
#    container_name: nginx
#    ports:
#      - "127.0.0.1:80:80"
#    depends_on:
#      - backend